---
version: '3.6'
services:
  ide:
    image: webide/webide 
    networks:
      - public
    environment:
      USERNAME: denzuko
      EMAIL: ${EMAIL}
      TZ: ${TZ:-"UTC-6"}
      LANG: ${LANG_ALL:-"en_US.UTF-8"}
      LANGUAGE: ${LANG_ALL:-"en_US.UTF-8"}
      LANG_ALL: ${LANG_ALL:-"en_US.UTF-8"}
      DOMAINAME: ${DOMAINNAME:-"matrix.net"}
      HOSTNAME: ${HOSTNAME:-"webide"}
    deploy:
      labels:
        net.matrix.environment: ${ENVIRONMENT:-"development"}
        traefik.enabled: 1
        traefik.priority: 10
        traefik.network: public
        traefik.port: 8080
        traefik.frontend.rule: 'Host: ${HOSTNAME}.${DOMAINNAME}'
    volumes:
      - data

volumes:
  data: {}

networks:
  public:
    external: true
    name: public
...
